version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mens-shop-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mens_shop_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
